name: 'Summary - Publish test results'
description: 'Summary - Publish test results'
inputs:
  gist-token:
    required: true
    description: Personal access token for github gist
  gist-id:
    required: true
    description: Id for the badge gist
  label:
    required: true
    description: label for badge
  status:
    required: true
    description: Text status for the badge
  color:
    required: true
    description: Badge color
  file:
    required: true
    description: Name of the badge file

runs:
  using: "composite"
  steps:

    - name: Debug message
      shell: bash
      run: |
        echo " "
        echo "*****************************************************"
        echo "Create badge"
        echo "*****************************************************"
        echo " "            

    - name: Create badge
      uses: emibcn/badge-action@master
      with:
        label: ${{ inputs.label }}
        status: ${{ inputs.status }}
        color: ${{ inputs.color }}
        path: ${{ inputs.file }}
    
    - name: Debug message
      shell: bash
      run: |
        echo " "
        echo "*****************************************************"
        echo "Upload badge"
        echo "*****************************************************"
        echo " "

    - name: Upload badge to Gist
      uses: jpontdia/append-gist-action@master
      with:
        token: ${{ inputs.gist-token }}
        gistURL: "https://gist.githubusercontent.com/${{ github.repository_owner }}/${{ inputs.gist-id }}"
        file: ${{ inputs.file }}