name: 'Summary - Publish test results'
description: 'Summary - Publish test results'
inputs:
  github-organization:
    required: true
    description: Name of the github organization
  gist-token:
    required: true
    description: Personal access token for github gist
  gist-id:
    required: true
    description: Id for the badge gist
  status:
    required: true
    description: Text status for the badge
  color:
    required: true
    description: Badge color
  file:
    required: true
    description: Name of the badge file

runs:
  using: "composite"
  steps:

    - name: Debug message
      shell: bash
      run: |
        echo " "
        echo "*****************************************************"
        echo "* Create badge"
        echo "*****************************************************"
        echo " "            

    - name: Create badge
      # uses: emibcn/badge-action@d6f51ff11b5c3382b3b88689ae2d6db22d9737d1
      uses: emibcn/badge-action@master
      with:
        label: Unit test
        status: ${{ inputs.status }}
        color: ${{ inputs.color }}
        path: ${{ inputs.file }}
    
    - name: Debug message
      shell: bash
      run: |
        echo " "
        echo "*****************************************************"
        echo "* Upload badge"
        echo "*****************************************************"
        echo " "            

    # Just testing this other action
    - name: Upload badge to Gist
      if: ${{ false }}
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ inputs.gist-token }}
        gist_id: ${{ inputs.github-organization }}/${{ inputs.gist-id }}
        file_path: ${{ steps.service-info.outputs.name }}-ut.svg
        file_type: binary

    - name: Upload badge to Gist
      uses: jpontdia/append-gist-action@master
      with:
        token: ${{ inputs.gist-token }}
        gistURL: "https://gist.githubusercontent.com/${{ inputs.github-organization }}/${{ inputs.gist-id }}"
        file: ${{ inputs.file }}