name: 'Summary - Publish test results'
description: 'Summary - Publish test results'
inputs:
  gist-token:
    required: true
    description: Personal access token for github gist
  gist-token-keyvault:
    required: false
    description: Personal access token for github gist
  github-organization:
    required: true
    description: Name of the github organization
  badge-gist-id:
    required: true
    description: Id for the badge gist
  debug:
    required: false
    type: boolean
    default: false
    description: Flag to debug this action, default is false

runs:
  using: "composite"
  steps:
 
    - name: DEBUG
      if: ${{ inputs.debug }}
      shell: bash
      run: |
        echo " "
        echo "*****************************************************"
        echo "* Summary - Publish test results"
        echo "*****************************************************"
        echo "Input variables: "
        echo "  gist-token: $(echo ${{inputs.gist-token}} | sed 's/./& /g')"  
        echo "  gist-token-keyvault: $(echo ${{inputs.gist-token-keyvault}} | sed 's/./& /g')"  
        echo "  github-organization: ${{ inputs.github-organization }}"
        echo "  badge-gist-id: ${{ inputs.badge-gist-id }}"
        echo ".."

    - name: Get the pom service information
      id: service-info
      uses: jpontdia/common-devops/packages/service-info@main

    - name: Summary - Publish test results
      id: unit-test-results
      uses: EnricoMi/publish-unit-test-result-action@v2.7.0
      if: always()
      with:
        files: |
          target/surefire-reports/*.xml
        check_name: Unit Test Results

    - name: Set badge color
      if: ${{ inputs.gist-token != '' }}
      shell: bash
      run: |
        case ${{ fromJSON( steps.unit-test-results.outputs.json ).conclusion }} in
          success)
            echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
            ;;
          failure)
            echo "BADGE_COLOR=800000" >> $GITHUB_ENV
            ;;
          neutral)
            echo "BADGE_COLOR=696969" >> $GITHUB_ENV
            ;;
        esac

    - name: Create badge
      if: ${{ inputs.gist-token != '' }}
      uses: jpontdia/common-devops/packages/badge@main
      with:
        gist-token: ${{ inputs.gist-token }}
        github-organization: ${{ inputs.github-organization }}
        badge-gist-id: ${{ inputs.badge-gist-id }}
        status: '${{ fromJSON( steps.unit-test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.unit-test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.unit-test-results.outputs.json ).conclusion }}'
        color: ${{ env.BADGE_COLOR }}
        file: ${{ steps.service-info.outputs.name }}-ut.svg
