name: Get secrets from Azure Key Vault
description: Get secrets from Azure Key Vault
inputs:
  keyvault-key:
    required: true
    description: The name of the KeyVault
  azure-credentials:
    required: true
    description: Azure Credentials for login
  secret-mapping:
    required: true
    description: Secret mapping file


runs:
  using: "composite"
  steps:

    - name: Debug action variables
      shell: bash
      run: |
        echo " "
        echo "*********************************************"      
        echo "Debug action variables"
        echo "*********************************************"
        echo " "
        tempvar=$( echo "${{ inputs.azure-credentials }}" | sed 's/./& /g' )
        echo "  azure-credentials: ${{ inputs.azure-credentials }}"
        echo "  keyvault-key: ${{ inputs.keyvault-key }}"
        echo "  secret-mapping: ${{ inputs.secret-mapping }}"
        echo " "

    - name: Authentication with Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure-credentials }}
        
    - name: Test Azure CLI
      shell: bash
      run: |
        echo "  "
        echo "  az version"
        az version
        echo "  "
        echo "  az webapp"
        az webapp list --query "[?state=='Running']"

    - name: Get configuration files
      uses: CoveredCA/common-devops/packages/get-file@main
      with:
        file: ${{ inputs.secret-mapping }}
        checkIfExists: true

    - name: Get secrets configuration
      shell: bash
      run: |
        echo " "
        echo "*********************************************"
        echo "Parse the secrets mapping file"
        echo "*********************************************"
        echo " "
        echo "  secret mapping: $configuration_data"

        temporal=""
        echo "$configuration_data" | while read p; do
          if [[ "$p" =~ ^#.*  ]]; then
            echo "   A comment found"
          else
            temporal=$(echo "$temporal $p")
            echo "   Variable found: $p"
          fi
          echo "$temporal" > configurationmap.txt
        done 

        echo ""
        configurationmap=$(cat configurationmap.txt)
        echo "Configuration file to get the secrets: $configurationmap"
        echo ""

    - name: Get Azure KeyVault
      uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
      with:
        keyvault: '${{ inputs.keyvault-key }}'
        secrets_file_path: configurationmap.txt