name: 'Configure the test and package command for maven'
description: 'Configure the test and package command for maven'
inputs:
  github-configurations-accesstoken:
    required: true
    description: Token to access the configuration repository
  github-organization:
    required: true
    description: Name of the github organization that is used to locate the secrets mapping file
  configurations-repository:
    required: true
    description: Name of the repository for mulesoft configurations
outputs:
  command:
    description: "Test and package command for maven"
    value: ${{ steps.configuration.outputs.command }}
runs:
  using: "composite"
  steps:
       
  - id: configuration-skiptest
    name: Get the skiptest property for the service
    uses: jpontdia/common-devops/packages/configuration-file@main
    with:
      github-configurations-accesstoken: $github_configurations_accesstoken
      yaml-path: ".skiptests"
      github-organization: ${{ inputs.github-organization }}
      configurations-repository: ${{ inputs.configurations-repository }} 

  - name: Get the properties for test cases
    id: configuration-tests
    uses: jpontdia/common-devops/packages/configuration-file@main
    with:
      github-configurations-accesstoken: $github_configurations_accesstoken
      yaml-path: ".test-properties"
      github-organization: $GITHUB_ORGANIZATION
      configurations-repository: $CONFIGURATIONS_REPOSITORY

  - name: Run test cases and package
    shell: bash
    run: |
      echo " "
      echo "***********************************************"
      echo "* Run test cases and package
      echo "***********************************************"
      echo " "
      echo "skiptest output: >${{steps.configuration-skiptest.outputs.configuration-data}}<"
      skiptest=" "
      if [[ "${{ steps.configuration-skiptest.outputs.configuration-data }}" == "true" ]]; then
        skiptest="-DskipTests"
        echo "  Test will be skipped"
      else
        echo "  Asset will be tested"
      fi

      mvn --batch-mode $skiptest package ${{ steps.configuration-tests.outputs.configuration-data }}
 