on:
  workflow_dispatch:
    inputs:
      write:
        description: "Change to 'true' to create issues, leave as 'false' to preview output"
        default: "false"
        type: boolean

name: Bulk issue creator

jobs:
  bulk_issue_creator:
    runs-on: ubuntu-latest
    name: Bulk Issue Creator
    steps:
      - name: Get token from Github App
        id: app-token
        uses: CoveredCA/common-devops/packages/app-token@main
        with:
          client-id: ${{ secrets.MULESOFT_GITHUBAPP_CLIENTID}}
          privatekey: ${{ secrets.MULESOFT_GITHUBAPP_PRIVATEKEY }}
      - name: Checkout template and data
        uses: actions/checkout@v2
      - name: Create bulk issues
        uses: benbalter/bulk-issue-creator@v2
        with:
          write: ${{ github.event.inputs.write }}
          github_token: ${{ env.github_automationbot_token }}
          csv_path: .github/workflows/issue_batch_creator/templates/test.csv