name: "Issue Batch New Repository"
description: "Create a batch of issues for a brand new repository"
inputs:
  write:
    description: "Change to 'true' to create issues, leave as 'false' to preview output"
    default: "false"
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Checkout template and data
      uses: actions/checkout@v2

    - name: Create bulk issues
      uses: benbalter/bulk-issue-creator@v2
      with:
        write: ${{ github.event.inputs.write }}
        github_token: ${{ env.github_automationbot_token }}
        csv_path: issue_batch_templates/test.csv
# TODO write script step to dynamically overwrite the repository with provided application name or use the template syntax for that
# TODO
# TODO
# TODO
