name: 'Install Mulesoft Anypoint CLI'
description: 'Install Mulesoft Anypoint CLI'

runs:
  using: "composite"
  steps:
    - name: Install NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Anypoint CLI
      run: |
        echo "Install anypoint-cli-v4..."
        npm install -g anypoint-cli-v4
        echo "anypoint-cli-v4 --version: "
        anypoint-cli-v4 --version
        echo ""
        echo "Installing cloudhub-plugin"
        anypoint-cli-v4 plugins:install anypoint-cli-cloudhub-plugin
        echo ""
      shell: bash