name: 'Get global configuration'
description: 'Get the global configuration and secrets from Azure KeyVault'
inputs:
  keyvault-key:
    required: true
    description: The name of the KeyVault
  azure-credentials:
    required: true
    description: Azure Credentials for login
  github-organization:
    required: true
    description: Name of the github organization that is used to locate the secrets mapping file
  configurations-repository:
    required: true
    description: Name of the repository for mulesoft configurations
runs:
  using: "composite"
  steps:

    - name: DEBUG - Show action variables
      if: ${{ false }}
      shell: bash
      run: |
        echo "DEBUG variables"
        tempvar=$( echo "${{ inputs.azure-credentials }}" | sed 's/./& /g' )
        echo "Value for inputs.azure-credentials: $tempvar" 

    # Note: if not sure if azure-credentials variable is not well configured, then try github action:
    # dmitriybobrovskiy/get-azure-keyvault-secrets, will show more details when authenticating 

    - name: DEBUG - Authentication with Azure
      if: ${{ false }}
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}
 
    - name: Get the access token to read files on configuration repository
      uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
      with:
        keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
        secrets: |
          github_gist_accesstoken=github-gist-accesstoken
          github_configurations_accesstoken=github-configurations-accesstoken
        login_credentials: ${{ inputs.azure-credentials }}

    - name: Get secrets configuration
      shell: bash
      env:
        SECRET_MAP_FILE: secrets-mapping.txt 
      run: |
        echo
        echo "*********************************************"
        echo "Get secrets map"
        echo "*********************************************"

        echo "github_configurations_accesstoken: $github_configurations_accesstoken"

        # Get the secrets mapping
        urlconfigurationfile="https://raw.githubusercontent.com/${{ inputs.github-organization }}/${{ inputs.configurations-repository }}/main/$SECRET_MAP_FILE"
        echo "Getting the secrets mapping file: $urlconfigurationfile"
        initialsecretconfiguration=$(curl -sH "Authorization: token $github_configurations_accesstoken" $urlconfigurationfile)

        temporal=""
        echo "$initialsecretconfiguration" | while read p; do
          if [[ "$p" =~ ^#.*  ]]; then
            echo "   A comment found"
          else
            temporal=$(echo "$temporal $p")
            echo "   Variable found: $p"
          fi
          echo "$temporal" > configurationmap.txt
        done 

        echo ""
        configurationmap=$(cat configurationmap.txt)
        echo "Configuration file to get the secrets: $configurationmap"
        
        # Enable only for debug
        # echo "initialsecretconfiguration: $initialsecretconfiguration"
        echo ""


    - name: Get Azure KeyVault
      uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
      with:
        keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
        secrets_file_path: configurationmap.txt

    - name: Get global configuration
      shell: bash
      env:
        SECRET_MAP_FILE: global.yml
      run: |
        echo
        echo "*********************************************"
        echo "Get global configuration"
        echo "*********************************************"

        echo "github_configurations_accesstoken: $github_configurations_accesstoken"

        # Get the configuration file from the github repository
        urlconfigurationfile="https://raw.githubusercontent.com/${{ inputs.github-organization }}/${{ inputs.configurations-repository }}/main/$SECRET_MAP_FILE"
        echo "Getting the secrets mapping file: $urlconfigurationfile"
        initialsecretconfiguration=$(curl -sH "Authorization: token $github_configurations_accesstoken" $urlconfigurationfile)

        # Verify if configuration file was found
        if [[ $configurationdata != *"Not Found"* ]]; then
          echo "A configuration file for the service was found"
          
          # Write the configuration file in the filesystem
          echo "$initialsecretconfiguration" > global.yml
        else
          echo "No configuration file found, returning an empty file"
          touch global.yml
        fi

    - name: Import vars example
      uses: zlatko-ms/varfiletoenv@v3
      with:
        paths: global.yml
