name: 'Install Java for Mulesoft Applications'
description: 'Install Java for Mulesoft Applications'
inputs:
  github-configurations-accesstoken:
    required: true
    description: Token to access the configuration repository
  default-settings-xml:
    required: true
    description: Default file for settings.xml in case the service doesn't have any configured
  github-organization:
    required: true
    description: Name of the github organization that is used to locate the secrets mapping file
  configurations-repository:
    required: true
    description: Name of the repository for mulesoft configurations
runs:
  using: "composite"
  steps:

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
              
    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        #check-latest: true
        cache: 'maven'

    - id: configuration
      name: Get configuration for the service 
      shell: bash
      run: |
        echo " "
        echo "*********************************************"
        echo "Get the settings configuration file for maven"
        echo "*********************************************"
        echo " "
        settings_xml=${{ inputs.default-settings-xml}}

        if [ "$configuration_settings" = "null" ] || [ "$configuration_settings" = "" ] ; then
          echo "The settings.xml file was not configured for the service, assigning the default one"
        else
          settings_xml=$settings_xml_temp
        fi

        echo "The maven settings file is: $settings_xml"
        echo "Reading the settings file from the configuration repository"
        urlconfigurationfile="https://raw.githubusercontent.com/${{ inputs.github-organization }}/${{ inputs.configurations-repository }}/main/$settings_xml"
        echo "URL file: $urlconfigurationfile"
        configurationdata=$(curl -sH "Authorization: token ${{inputs.github-configurations-accesstoken}}" $urlconfigurationfile)
        echo "The content of the file is: $configurationdata"
        output=$(echo "$configurationdata" | envsubst)
        echo "$output" > $HOME/.m2/settings.xml

        echo "Verifying configuration"
        echo "HOME Directory: $HOME"" 
        ls -la $HOME
        temporal=$(cat $HOME/.m2/settings.xml)
        echo "settings.xml file: $temporal"