name: Update Deployment Issue
description: Deployment issues need custom project fields filled out
inputs:
  organization:
    required: false
    default: "CoveredCA"
    description: Name of the organization the project is in
  project-number:
    required: false
    default: 5
    description: The number of the project from the project web url
  application-name:
    required: true
    default: "cca-salesforce-sapi"
    description: The name of the application the deployment issue was created for
  version:
    required: true
    default: "1.0.10"
    description: The version of the application to be deployed to the environment
  token:
    required: true
    description: The token for the mulebot so that github api actions can be performed

runs:
  using: "composite"
  steps:

    - name: Get project ID
      id: project-id
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo ""
        echo "******************"
        echo "* Get Project ID *"
        echo "******************"
        echo ""
        PROJECT_ID=$(gh api graphql -f query='{
          organization(login: "${{ inputs.organization }}") {
            login
            projectsV2(first: 100) {
              edges {
                node {
                  id
                  title
                }
              }
            }
          }
        }' | jq -r '.data.organization.projectsV2.edges[] | select(.node.title | test("Deployment")) | .node.id')

        echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_OUTPUT

    - name: Get issue ID
      id: issue-id
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo ""
        echo "****************"
        echo "* Get Issue ID *"
        echo "****************"
        echo ""

        # Initial cursor is empty
        CURSOR=""

        # Loop until all pages are fetched
        while : ; do
            # Execute GraphQL query
            RESPONSE=$(gh api graphql -f query='
            query($org: String!, $number: Int!, $cursor: String) {
                organization(login: $org) {
                    projectV2(number: $number) {
                        items(first: 100, after: $cursor) {
                            pageInfo {
                                hasNextPage
                                endCursor
                            }
                            nodes {
                                id
                                content {
                                    ... on Issue {
                                        id
                                        number
                                        title
                                    }
                                }
                            }
                        }
                    }
                }
            }' -f org="${{ inputs.organization }}" -F number=${{ inputs.project-number }} -f cursor="$CURSOR")

            # Parse items and do something with them, e.g., append to a file
            echo "$RESPONSE" | jq '.data.organization.projectV2.items.nodes[]' >> scan-dependency-issues.json

            # Check if there's a next page; if not, break the loop
            HAS_NEXT_PAGE=$(echo "$RESPONSE" | jq '.data.organization.projectV2.items.pageInfo.hasNextPage')
            if [ "$HAS_NEXT_PAGE" != "true" ]; then
                break
            fi

            # Update cursor to fetch next page
            CURSOR=$(echo "$RESPONSE" | jq -r '.data.organization.projectV2.items.pageInfo.endCursor')
        done

        echo "All items fetched successfully."

        echo "Parsing output data file"
    - name: Check JSON Content
      run: cat scan-dependency-issues.json
        
        ISSUE_ID=$(jq -r '. | select(.content.title | test("scan-dependencies")) | select(.content.title | test("${{ inputs.application-name }}")) | select(.content.title | test("${{ inputs.version }}")) | .id' scan-dependency-issues.json)

        echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_OUTPUT

    - name: Get field IDs
      id: field-id
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo ""
        echo "******************"
        echo "* Get Field ID's *"
        echo "******************"
        echo ""

        FIELD_DATA=$(gh api graphql -f query='
                    query($org: String!, $number: Int!) {
                      organization(login: $org){
                        projectV2(number: $number) {
                          id
                          fields(first:20) {
                            nodes {
                              ... on ProjectV2Field {
                                id
                                name
                              }
                            ... on ProjectV2IterationField {
                            id
                            name
                            configuration {
                                iterations {
                                startDate
                                id
                                }
                            }
                            }
                              ... on ProjectV2SingleSelectField {
                                id
                                name
                                options {
                                  id
                                  name
                                }
                              }
                            }
                          }
                        }
                      }
                    }' -f org="${{ inputs.organization }}" -F number=${{ inputs.project-number }} | jq '.data.organization.projectV2.fields.nodes[] | select(.name | IN("Status"))')

        FIELD_ID_STATUS=$(echo "$FIELD_DATA" | jq -r '. | select(.name | test("Status")).id')
        FIELD_ID_STATUS_TODO_ID=$(echo "$FIELD_DATA" | jq -r '. | select(.name | test("Status")).options[] | select(.name=="Todo").id')

        echo "FIELD_ID_STATUS=$FIELD_ID_STATUS" >> $GITHUB_OUTPUT
        echo "FIELD_ID_STATUS_TODO_ID=$FIELD_ID_STATUS_TODO_ID" >> $GITHUB_OUTPUT

    - name: Update Issue Status Field
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo ""
        echo "*******************************"
        echo "* Updating Issue Status Field *"
        echo "*******************************"
        echo ""
        gh api graphql -f query='
            mutation {
                updateProjectV2ItemFieldValue(
                    input: {
                        projectId: "${{steps.project-id.outputs.PROJECT_ID}}"
                        itemId: "${{ steps.issue-id.outputs.ISSUE_ID }}"
                        fieldId: "${{ steps.field-id.outputs.FIELD_ID_STATUS }}"
                        value: {
                            singleSelectOptionId: "${{ steps.field-id.outputs.FIELD_ID_STATUS_TODO_ID }}"
                        }
                    }
                )
                {
                    projectV2Item {
                        id
                    }
                }
            }'
