name: 'Get secrets'
description: 'Get secrets from Azure KeyVault'
inputs:
  keyvault-key:
    required: true
    description: The name of the KeyVault
    type: string
  azure-credentials:
    required: true
    description: Azure Credentials for login
runs:
  using: "composite"
  steps:

    - name: Get secrets for the pipeline
      uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
      with:
        keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
        secrets: |
          configuration_access_token=configuration-access-token
          mulesoft_nexus_ee_password=mulesoft-nexus-ee-password
          mulesoft_nexus_ee_user=mulesoft-nexus-ee-user
          cicd_connectedapp_clientid=cicd-connectedapp-clientid
          cicd_connectedapp_secret=cicd-connectedapp-secret
        login_credentials: ${{ inputs.azure-credentials }}
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash