name: 'Get secrets from Azure KeyVault'
description: 'Get secrets from Azure KeyVault'
inputs:
  keyvault-key:
    required: true
    description: The name of the KeyVault
  azure-credentials:
    required: true
    description: Azure Credentials for login
runs:
  using: "composite"
  steps:

    - name: Get the configuration access token to read files on repository mule-configurations
      uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
      with:
        keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
        secrets: |
          configuration_access_token=configuration-access-token
        login_credentials: ${{ inputs.azure-credentials }}

    - name: Get the mapping for the secrets 
      run: |
        #Configure environment variables
        echo "configuration_access_token: $configuration_access_token"

        # Get the secrets mapping
        secretsmappingfile="secrets-mapping.txt"
        urlconfigurationfile="https://raw.githubusercontent.com/jpontdia/mule-configurations/main/$secretsmappingfile"
        echo "Getting the secrets mapping file: $urlconfigurationfile"
        initialsecretconfiguration=$(curl -sH "Authorization: token $configuration_access_token" $urlconfigurationfile)

        temporal=""
        echo "$initialsecretconfiguration" | while read p; do
          if [[ "$p" =~ ^#.*  ]]; then
            echo "  A comment was found"
          else
            temporal=$(echo "$temporal $p")
            echo "  Variable found: $p"
          fi
          echo "$temporal" > configurationmap.txt
        done 

        echo ""
        configurationmap=$(cat configurationmap.txt)
        echo "configurationmap: $configurationmap"
        echo "initialsecretconfiguration: $initialsecretconfiguration"
      shell: bash

    - name: Get Azure KeyVault secrets for the service
      uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
      with:
        keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
        secrets_file_path: configurationmap.txt
