##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  DEFAULT_SETTINGS_XML: settings.xml
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations

jobs:

  ##########################################################################
  # TEST BAT
  ##########################################################################

  BAT:
    name: BAT
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write    
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: test xml in bash
        shell: bash
        run: |
          echo "Getting service info from pom.xml "
          sudo apt-get install -y libxml2-utils
          echo " "
          echo " first command "
          # xmllint --xpath "//*[local-name()='project']//*[local-name()='name'" pom.xml

          xmllint --xpath "/*[local-name()='project']/*[local-name()='name'" pom.xml
          
          echo " "
          echo " first command "
          xmllint --xpath "//*[local-name()='project']/version" pom.xml
          echo "end...."


      - name: Get service name
        id: service-name
        uses: mavrosxristoforos/get-xml-info@1.2.0
        with:
          xml-file: 'pom.xml'
          xpath: '//project/name'

      - name: Get service name
        id: service-version
        uses: mavrosxristoforos/get-xml-info@1.2.0
        with:
          xml-file: 'pom.xml'
          xpath: '//project/version'

      - name: Debug service xml
        shell: bash
        run: |
          echo "Show environment variables "
          echo "service_name: " ${{ steps.service-name.outputs.info }}
          echo "service_version: " ${{ steps.service-version.outputs.info }}
          echo "end...."
