##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: deployment
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  release:
    name: deployment
    runs-on: ubuntu-latest
    steps:

      - name: Get the release metadata
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}      
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Debug "
          echo "***********************************************"
          echo " "
          echo "issue.number: ${{ github.event.issue.number}}"
          echo " "
          echo "Title: ${{ github.event.issue.title}}"
          echo " "
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"
          echo " "
          echo " "
          echo " "
          echo " "
          echo "$GITHUB_CONTEXT"

      - name: Get the source code
        uses: actions/checkout@v4
        #with:
        #  ref: ''

#      - uses: dsaltares/fetch-gh-release-asset@master
#        with:
#          repo: 'dsaltares/godot-wild-jam-18'
#          version: 'tags/v0.1.18'
#          regex: true
#          file: "plague-.*\\.zip"
#          target: 'subdir/'
#          token: ${{ secrets.GITHUB_TOKEN }}