name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
      gist-accesstoken:
        required: false
        description: Github Gist personal access token
env:
  DEFAULT_SETTINGS_XML: settings.xml
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: mulesoft-configurations
  GIST_ID: ef8cdef1ff940eac4d8716f6361d2363
jobs:

  ##########################################################################
  # BUILD MULESOFT SERVICE
  ##########################################################################

  build:
    name: Build
    runs-on: ubuntu-latest
    # Needed by the Unit Test Action
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write    
    outputs:
      # Indicates if the service will be deployed to development environment
      deployment: ${{ steps.verify-deployment.outputs.deployment }}
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: Install Java JDK for Mulesoft Applications
        uses: jpontdia/mulesoft-pipeline/packages/install-mulesoft-java@main

      - name: Get default secrets for the pipeline
        uses: jpontdia/mulesoft-pipeline/packages/secrets@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY

      - name: Settings file for maven
        uses: jpontdia/mulesoft-pipeline/packages/settings-maven@main
        with:
          github-configurations-accesstoken: $github_configurations_accesstoken
          default-settings-xml: $DEFAULT_SETTINGS_XML
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          
      - name: Documentation - Anypoint Exchange
        run: |
          cp -Rfpv README.md exchange-docs/home.md
          cp -Rfpv docs/*.* exchange-docs/docs 
        
      - name: Compile code
        #if: ${{ false }}    
        run: mvn --batch-mode compile
  
      - name: Run test cases and package asset
        uses: jpontdia/mulesoft-pipeline/packages/package@main
        with:
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          github-configurations-accesstoken: $github_configurations_accesstoken

      - name: Summary - Unit test cases
        uses: jpontdia/mulesoft-pipeline/packages/summary-testcases@main
        with:
          gist-token: ${{ secrets.gist-accesstoken }}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          badge-gist-id: ${{ env.GIST_ID }}
          debug: "false"

      - name: Summary - Code coverage
        uses: jpontdia/mulesoft-pipeline/packages/summary-codecoverage@main
        with:
          gist-token: ${{ secrets.gist-accesstoken }}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          badge-gist-id: ${{ env.GIST_ID }}

      - name: Deploy to anypoint exchange
        #if: ${{ false }}    
        run: |
          ## Deploy to anypoint exchange
          mvn --batch-mode deploy -DskipTests 

      - name: Publish - Application Coverage Report
        #if: ${{ false }}    
        uses: actions/upload-artifact@master
        with:
          name: munit-application-coverage-report
          path: target/site/munit/coverage/*
      
      - name: Publish - MUnit Report
        #if: ${{ false }}
        uses: actions/upload-artifact@master
        with:
          name: munit-test-report
          path: target/surefire-reports/*

      - name: Publish - JAR 
        uses: actions/upload-artifact@master
        with:
          name: jar
          path: target/*.jar

      - name: Publish - POM 
        uses: actions/upload-artifact@master
        with:
          name: pom
          path: pom.xml
          
      - id: dev-configuration-cloudhub
        name: Deployment dev - Get configuration
        uses: jpontdia/mulesoft-pipeline/packages/configuration-file@main
        with:
          github-configurations-accesstoken: $github_configurations_accesstoken
          yaml-path: ".cloudhub"
          suffix: "-dev"
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY          

      - id: verify-deployment
        name: Deployment dev - Verify if asset has the configuration
        run: |
          echo "dev cloudhub: ${{ steps.dev-configuration-cloudhub.outputs.configuration-data }}"
          if [ "${{ steps.dev-configuration-cloudhub.outputs.configuration-data }}" != "" ] ; then
            echo "deployment=true" >> $GITHUB_OUTPUT
            echo "The service has the configuration to deploy in development environment"
          else
            echo "deployment=false" >> $GITHUB_OUTPUT
            echo "The mulesoft asset doesn't have any deployment configuration"
          fi
  
  ##########################################################################
  # DEPLOYMENT TO DEV
  ##########################################################################
  
  deploy-dev:
    if: needs.build.outputs.deployment == 'true'
    name: DEV
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:

      - name: Deploy the service in the cloud
        uses: jpontdia/mulesoft-pipeline/packages/cloudhub-deployment@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          deployment-env: dev


  ##########################################################################
  # INTEGRATION TESTING - DEVELOPMENT
  ##########################################################################

  testing-dev:
    name: DEV Test
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    steps:
      - name: Get the source code
        uses: actions/checkout@v3

      - name: Install API Functional Monitoring
        run: |
          curl -o- 'https://s3.amazonaws.com/bat-wrapper/install.sh' | bash
          echo "bat -version: $(bat -version)"

      - name: Run tests
        run: |
          cd bat
          mkdir target
          bat

      - name: Publish - Test reports
        # if: ${{ false }}    
        uses: actions/upload-artifact@master
        with:
            name: dev-testing-reports
            path: bat/target/*.*

      - name: Job summary with test results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        if: always()
        with:
          files: |
            bat/target/JUnit.xml
          check_name: Dev Integration Test

  ##########################################################################
  # TESTING ENVIRONMENT
  ##########################################################################
  
  deploy-tst:
    name: TST
    needs: [testing-dev]
    runs-on: ubuntu-latest
    environment:
      name: tst
    steps:

      - name: Deploy the service in the cloud
        uses: jpontdia/mulesoft-pipeline/packages/cloudhub-deployment@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          deployment-env: tst
