##########################################################################
# Mulesoft CICD Pipeline - Deploy Mulesoft Application
##########################################################################

name: CustomLogging
on:
  workflow_call:

env:
  CONFIGURATIONS_REPOSITORY: common-configurations
  GLOBAL_CONFIGURATION: _global.yml
  SECRETS_AZURE_KEYVAULT: CoveredCA-KV-Mulesoft
  MESSAGE_SERVICE_SUCCESS_DEPLOYED: "The service was successfully deployed"
  MESSAGE_SERVICE_INTERNAL_ERROR: "There was an internal error in the deployment process"

jobs:

  CustomLogging:
    name: CustomLogging
    runs-on: ubuntu-latest

    steps:

      - name: Get token from Github App
        id: app-token
        uses: CoveredCA/common-devops/packages/app-token@main
        with:
          client-id: ${{ secrets.MULESOFT_GITHUBAPP_CLIENTID}}
          privatekey: ${{ secrets.MULESOFT_GITHUBAPP_PRIVATEKEY }}

      - name: Get secrets from Azure Key Vault
        id: secrets
        uses: CoveredCA/common-devops/packages/secrets-azure@main
        with:
          keyvault-key: ${{ env.SECRETS_AZURE_KEYVAULT}}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get service configuration
        uses: CoveredCA/common-devops/packages/configuration-service@main

      - name: Get jar file
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: '${{ github.repository }}'
          version: 'tags/${{ env.deployment_version }}'
          regex: false
          file: "${{ env.service_artifact }}-${{ env.deployment_version }}-${{ env.configuration_apptype }}.jar"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug show root files
        id: debug-show-root-files
        shell: bash
        run: |
          echo " "
          echo "***************************************"
          echo "Debug show root files"
          echo "***************************************"
          echo " "
          ls -l

      - name: Custom Logging
        id: custom-logging
        uses: CoveredCA/common-devops/packages/customlogger@main
        with:
          deployment-env: ${{ env.deployment_environment }}

      - name: Create badge for custom logging
        uses: CoveredCA/common-devops/packages/badge@main
        with:
          label: '${{ env.deployment_environment }} custom log'
          status: 'true'
          color: '535597'
          file: ${{ env.service_name }}-${{ env.deployment_environment }}-cl.svg
          folder: ${{ env.service_name }}
