##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  DEFAULT_SETTINGS_XML: settings.xml
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  ##########################################################################
  # BUILD MULESOFT SERVICE
  ##########################################################################

  build:
    name: Build
    runs-on: ubuntu-latest
    # Needed by the Unit Test Action
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write    
    outputs:
      # Indicates if the service is deployable
      deployment-dev: ${{ steps.verify-deployment-dev.outputs.deployment }}
      deployment-tst: ${{ steps.verify-deployment-tst.outputs.deployment }}
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: Install Java JDK for Mulesoft Applications
        uses: jpontdia/common-devops/packages/install-mulesoft-java@main

      - name: Get global configuration for the pipeline
        uses: jpontdia/common-devops/packages/configuration@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY

      - name: Settings file for maven
        uses: jpontdia/common-devops/packages/settings-maven@main
        with:
          github-configurations-accesstoken: $github_configurations_accesstoken
          default-settings-xml: $DEFAULT_SETTINGS_XML
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          
      - name: Documentation - Anypoint Exchange
        run: |
          if [ -d "exchange-docs" ] 
            then
              echo "Directory exchange-docs exists and will not be overriden with README.md" 
            else
              mkdir -p exchange-docs
              mkdir -p exchange-docs/docs
              cp -Rfpv README.md exchange-docs/home.md
              cp -Rfpv docs/*.* exchange-docs/docs 
            fi
        
      - name: Compile code
        #if: ${{ false }}    
        run: mvn --batch-mode compile
  
      - name: Run test cases and package asset
        uses: jpontdia/common-devops/packages/package@main
        with:
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          github-configurations-accesstoken: $github_configurations_accesstoken

      - name: Debug - global variables
        #if: ${{ false }}    
        run: |
          ## Global variables
          echo "gist_id: " $cicd_gist_id 
          echo "cicd_debug: " $cicd_debug 

      # To investigate. When sending badge-gist-id as $cicd_gist_id IS NOT working only in this step
      # only works with: ${{ env.cicd_gist_id }}
      - name: Summary - Unit test cases
        if: ${{ hashFiles('target/surefire-reports/*') != '' }}
        uses: jpontdia/common-devops/packages/summary-testcases@main
        with:
          gist-token: ${{ env.github_gist_accesstoken }}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          badge-gist-id: ${{ env.github_gist_id }}
          debug: ${{ env.cicd_debug }}

      - name: Summary - Code coverage
        uses: jpontdia/common-devops/packages/summary-codecoverage@main
        with:
          gist-token: ${{ env.github_gist_accesstoken }}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          badge-gist-id: ${{ env.github_gist_id }}
          debug: ${{ env.cicd_debug }}


      - name: Deploy to anypoint exchange
        #if: ${{ false }}    
        run: |
          ## Deploy to anypoint exchange
          mvn --batch-mode deploy -DskipTests 

      - name: Publish - Application Coverage Report
        #if: ${{ false }}
        if: ${{ hashFiles('target/site/munit/coverage/*') != '' }}
        uses: actions/upload-artifact@master
        with:
          name: munit-application-coverage-report
          path: target/site/munit/coverage/*
      
      - name: Publish - MUnit Report
        #if: ${{ false }}
        if: ${{ hashFiles('target/surefire-reports/*') != '' }}
        uses: actions/upload-artifact@master
        with:
          name: munit-test-report
          path: target/surefire-reports/*

      - name: Publish - JAR 
        uses: actions/upload-artifact@master
        if: ${{ hashFiles('target/*.jar') != '' }}
        with:
          name: jar
          path: target/*.jar

      - name: Publish - POM 
        uses: actions/upload-artifact@master
        with:
          name: pom
          path: pom.xml
          
      - id: verify-deployment-dev
        name: Verify if asset is deployable in dev
        uses: jpontdia/common-devops/packages/verify-deployment@main
        with:
          github-configurations-accesstoken: $github_configurations_accesstoken
          environment: dev
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
  
      - id: verify-deployment-tst
        name: Verify if asset is deployable in tst
        uses: jpontdia/common-devops/packages/verify-deployment@main
        with:
          github-configurations-accesstoken: $github_configurations_accesstoken
          environment: tst
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY

  ##########################################################################
  # DEV DEPLOYMENT
  ##########################################################################
  
  dev:
    if: needs.build.outputs.deployment-dev == 'true'
    name: dev
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:

      - name: Deploy the service in the cloud
        uses: jpontdia/common-devops/packages/cloudhub-deployment@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          deployment-env: dev


  ##########################################################################
  # DEV TEST
  ##########################################################################

  dev-test:
    name: dev-test
    needs: [dev]
    runs-on: ubuntu-latest
    steps:
      - name: Get the source code
        uses: actions/checkout@v3

      - name: Verify if running test
        id: verify-testing
        run: |
          if [ -d "bat" ]; then
            # BAT script exist, the complete action will be executed
            echo "SKIP_TEST=false" >> $GITHUB_OUTPUT
          else
            # Integration testing doesn´t exist
            echo "SKIP_TEST=true" >> $GITHUB_OUTPUT
          fi

      - name: Get global configuration for the pipeline
        if: steps.verify-testing.outputs.SKIP_TEST == 'false'
        uses: jpontdia/common-devops/packages/configuration@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
        
      - name: Execute Mulesoft BAT
        if: steps.verify-testing.outputs.SKIP_TEST == 'false'
        uses: jpontdia/common-devops/packages/bat@main

      - name: Publish - Test reports
        if: always() && steps.verify-testing.outputs.SKIP_TEST == 'false'
        uses: actions/upload-artifact@master
        with:
            name: dev-testing-reports
            path: bat/target/*.*

      - name: Job summary with test results
        if: always() && steps.verify-testing.outputs.SKIP_TEST == 'false'
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        with:
          files: |
            bat/target/JUnit.xml
          check_name: Dev Integration Test

  ##########################################################################
  # TST DEPLOYMENT
  ##########################################################################
  
  tst:
    if: needs.build.outputs.deployment-tst == 'true'
    name: tst
    needs: [dev-test]
    runs-on: ubuntu-latest
    environment:
      name: tst
    steps:

      - name: Deploy the service in the cloud
        uses: jpontdia/common-devops/packages/cloudhub-deployment@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY
          deployment-env: tst
