##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: deployment
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations
  DEPLOYMENT_FORWARD_LABEL: deployment-forward
  MESSAGE_ASSET_NOT_CONFIGURED: "The mulesoft asset doesn't have any deployment configuration"
  MESSAGE_SERVICE_INTERNAL_ERROR: "There was an internal error in the deployment process"
  MESSAGE_SERVICE_NOT_DEPLOYED: "The service couldn't be deployed"
  MESSAGE_SERVICE_SUCCESS_DEPLOYED: "The service was successfully deployed"

jobs:

  ##################################################################
  # Analyse deployment of service
  ##################################################################
  verify:
    if: github.actor == 'jpontdia' || github.actor == 'GitHubActions'
    name: verify
    runs-on: ubuntu-latest
    outputs:
      # Indicates if the service is deployable
      deployment: ${{ steps.verify-deployment.outputs.deployment }}

    steps:
      - name: Get workflow metadata
        uses: jpontdia/common-devops/packages/workflow-metadata@main
        with:
          keyvault-key: '${{ inputs.keyvault-key }}'
          azure-credentials: '${{ secrets.azure-credentials }}'
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}

      - id: verify-deployment
        name: Verify if asset has the deployment configuration
        shell: bash
        run: |
          echo " "
          echo "*****************************************************"
          echo "Verify deployment to ${{ env.deployment_environment }} "
          echo "*****************************************************"
          echo " "      
          echo "dev cloudhub: ${{ env.configuration_cloudhub }}"
          if [ "${{ env.configuration_cloudhub }}" != "" ] ; then
            echo "deployment=true" >> $GITHUB_OUTPUT
            echo "The service has the configuration to be deployed in ${{ env.deployment_environment }} environment"
            echo
          else
            echo "deployment=false" >> $GITHUB_OUTPUT
            issue_message="${{env.MESSAGE_ASSET_NOT_CONFIGURED}}"
            echo "$issue_message"
            echo "issue_message=$issue_message" >> $GITHUB_ENV
          fi

      - id: issue-close
        name: Close issue
        if: steps.verify-deployment.outputs.deployment == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Update Issue: ${{ github.event.issue.number }} "
          echo "***********************************************"
          echo " "
          gh issue close ${{ github.event.issue.number }} \
            -c "$issue_message" \
            -r "not planned"

  ##################################################################
  # Deployment
  ##################################################################
  deployment:
    needs: [verify]
    if: needs.verify.outputs.deployment == 'true'
    name: deployment
    runs-on: ubuntu-latest
    outputs:
      # Indicates if the service was deployed
      outcome: ${{ steps.deployment-ch1.outputs.outcome }}

    steps:
      - name: Get workflow metadata
        uses: jpontdia/common-devops/packages/workflow-metadata@main
        with:
          keyvault-key: '${{ inputs.keyvault-key }}'
          azure-credentials: '${{ secrets.azure-credentials }}'
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}
      
      - name: Get jar file
        uses: dsaltares/fetch-gh-release-asset@master
        if: steps.verify-deployment.outputs.deployment == 'true'
        with:
          repo: '${{ github.repository }}'
          version: 'tags/${{ env.deployment_version }}'
          regex: true
          file: "${{ env.deployment_service }}-.*\\.jar"
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: deployment-ch1
        name: Deploy the service in the cloud
        uses: jpontdia/common-devops/packages/process-deployment-ch1@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}
          deployment-env: ${{ env.deployment_environment }}

      - id: debug
        name: debug
        if: always()
        continue-on-error: true
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Debug.  steps.deployment-ch1.outputs.outcome: ${{ steps.deployment-ch1.outputs.outcome }} "
          echo "***********************************************"
          echo " "
                      
      - id: issue-close-deployment-error
        name: Close issue error on deployment
        if: steps.deployment-ch1.outputs.outcome == null
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Update Issue: ${{ github.event.issue.number }} "
          echo "***********************************************"
          echo " "
          gh issue close ${{ github.event.issue.number }} \
            -c "${{ env.MESSAGE_SERVICE_INTERNAL_ERROR }}" \
            -r "not planned"
          
      - id: issue-close-deployment
        name: Close issue error on deployment
        if: steps.deployment-ch1.outputs.outcome == 'failure'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Update Issue: ${{ github.event.issue.number }} "
          echo "***********************************************"
          echo " "
          gh issue close ${{ github.event.issue.number }} \
            -c "${{ env.MESSAGE_SERVICE_NOT_DEPLOYED }}" \
            -r "not planned"

  ##################################################################
  # Testing
  ##################################################################
  testing:
    needs: [deployment]
    if: needs.deployment.outputs.outcome != 'failure'
    name: testing
    runs-on: ubuntu-latest

    steps:
      - name: Get workflow metadata
        uses: jpontdia/common-devops/packages/workflow-metadata@main
        with:
          keyvault-key: '${{ inputs.keyvault-key }}'
          azure-credentials: '${{ secrets.azure-credentials }}'
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}

      - name: Execute Mulesoft BAT
        uses: jpontdia/common-devops/packages/process-bat@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}
          deployment-env: ${{ env.deployment_environment }}

      - id: issue-close-success
        name: Close issue success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Update Issue: ${{ github.event.issue.number }} "
          echo "***********************************************"
          echo " "
          gh issue close ${{ github.event.issue.number }} \
            -c "${{ env.MESSAGE_SERVICE_SUCCESS_DEPLOYED }}" \
            -r "completed"

  ##################################################################
  # Forward to next environnment
  ##################################################################
  forward:
    needs: [testing]
    if: needs.deployment.outputs.outcome != 'failure'
    name: forward
    runs-on: ubuntu-latest

    steps:
      - name: Get workflow metadata
        uses: jpontdia/common-devops/packages/workflow-metadata@main
        with:
          keyvault-key: '${{ inputs.keyvault-key }}'
          azure-credentials: '${{ secrets.azure-credentials }}'
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}

      - name: Create badge for deployment
        uses: jpontdia/common-devops/packages/build-badge@main
        with:
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          gist-id: ${{ env.github_gist_id }}
          gist-token: ${{ env.github_gist_accesstoken }}
          label: '${{ env.deployment_environment }} version'
          status: '${{ env.deployment_version }}'
          color: '535597'
          file: ${{ env.service_name }}-${{ env.deployment_environment }}.svg