##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
      gist-accesstoken:
        required: false
        description: Github Gist personal access token
env:
  DEFAULT_SETTINGS_XML: settings.xml
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations
  GIST_ID: ef8cdef1ff940eac4d8716f6361d2363

jobs:

  ##########################################################################
  # BUILD MULESOFT SERVICE
  ##########################################################################

  build:
    name: Build
    runs-on: ubuntu-latest
    # Needed by the Unit Test Action
    permissions: write-all
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: Install Java JDK for Mulesoft Applications
        uses: jpontdia/common-devops/packages/install-mulesoft-java@main

      - name: Get default secrets for the pipeline
        uses: jpontdia/common-devops/packages/configuration@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY

      - name: Settings file for maven
        uses: jpontdia/common-devops/packages/settings-maven@main
        with:
          github-configurations-accesstoken: $github_configurations_accesstoken
          default-settings-xml: $DEFAULT_SETTINGS_XML
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY

      - name: Summary - Unit test cases
        if: ${{ hashFiles('target/surefire-reports/*') != '' }}
        uses: jpontdia/common-devops/packages/summary-testcases@main
        with:
          gist-token: ${{ secrets.gist-accesstoken }}
          gist-token-keyvault: $github_gist_accesstoken
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          badge-gist-id: ${{ env.GIST_ID }}
          debug: "true"
