##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  DEFAULT_SETTINGS_XML: settings.xml
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations

jobs:

  ##########################################################################
  # TEST BAT
  ##########################################################################

  BAT:
    name: BAT
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write    
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: Get global configuration for the pipeline
        uses: jpontdia/common-devops/packages/configuration@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ secrets.azure-credentials }}
          github-organization: $GITHUB_ORGANIZATION
          configurations-repository: $CONFIGURATIONS_REPOSITORY

      - id: configuration-service
        name: Get the configuration properties for the service
        uses: jpontdia/common-devops/packages/configuration-file@main
        with:
          github-configurations-accesstoken: $github_configurations_accesstoken
          yaml-path: ".env"
          suffix: "-dev"
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}

      - name: Generate environment variables for the service
        shell: bash
        run: |
          echo "5. "
          echo "micorpcustomersapi_host: " $micorpcustomersapi_host
          export test_var="My value"
          echo " "

          service_configuration_raw='${{ steps.configuration-service.outputs.configuration-data }}'
          service_configuration_lines=$( echo $service_configuration_raw | tr ' ' '\n' )
          echo -e "Configuration formated:\n$service_configuration_lines "

          echo "$service_configuration_lines" | while read p; do
            # echo -e '$p' >> $GITHUB_ENV
            echo "export $p"
          done 
          echo "micorpcustomersapi_host: " $micorpcustomersapi_host


      - name: Debug
        shell: bash
        run: |
          echo "Show environment variables "
          echo "micorpcustomersapi_host: " $micorpcustomersapi_host
          echo "test_var: " $test_var
          echo "end...."

#      - name: Execute Mulesoft BAT
#        uses: jpontdia/common-devops/packages/bat@main
    
#      - name: Publish - Test reports
#        uses: actions/upload-artifact@master
#        with:
#            name: dev-testing-reports
#            path: bat/target/*.*

#      - name: Job summary with test results
#        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
#        with:
#          files: |
#            bat/target/JUnit.xml
#          check_name: Dev Integration Test