name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
      configurations-token:
        required: true
        description: Access token to get the configuration for the service
env:
  initialsecretconfiguration: ""
  configurationmap: "" 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      #For testing dynamic content
      MavenCompile: mvn compile

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Get the source code
        uses: actions/checkout@v3

      - name: Get secrets
        uses: jpontdia/devops-pipelines/packages/get-secrets@main
        with:
          keyvault-key: jpworks-keyvault
          azure-credentials: ${{ secrets.azure-credentials }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
                  
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          #check-latest: true
          cache: 'maven'

      # Creates a settings.xml file and configure the anypoint repositories for the organization and the mulesoft EE
      - name: Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: >
            [
              {
                "id": "anypoint-exchange-v3",
                "username": "~~~Client~~~",
                "password": "$cicd_connectedapp_clientid }}~?~$cicd_connectedapp_secret" 
              },
              {
                "id": "mulesoft-enterprise-repository",
                "username": "$mulesoft_nexus_ee_user",
                "password": "$mulesoft_nexus_ee_password" 
              }
            ]
          repositories: >
            [
              {
                "id": "anypoint-exchange-v3",
                "name": "Assets for your anypoint organization",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven/"
              },
              {
                "id": "mulesoft-releases",
                "name": "mulesoft-releases",
                "url": "https://repository-master.mulesoft.org/releases/"
              },
              {
                "id": "mulesoft-snapshots",
                "name": "MuleSoft Snapshot Repository",
                "url": "https://repository-master.mulesoft.org/snapshots/"
              },
              {
                "id": "mulesoft-enterprise-repository",
                "name": "MuleSoft Enterprise Repository",
                "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "mulesoft-plugins",
                "name": "Mulesoft plugins-release",
                "url": "https://repository.mulesoft.org/nexus/content/repositories/public/"
              },
              {
                "id": "central-plugins",
                "name": "plugins-release",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "mulesoft-snapshots",
                "name": "MuleSoft Snapshot Repository",
                "url": "https://repository-master.mulesoft.org/snapshots/"
              },
              {
                "id": "mulesoft-plugins-release",
                "name": "Mulesoft plugins-release",
                "url": "https://repository.mulesoft.org/releases/",
                "snapshots": {
                  "enabled": "false",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                }
              }              
            ]
        
      - name: DEBUG - Show settings file
        run: |
          ls -la $HOME
          cat $HOME/.m2/settings.xml
          echo ${{ github.run_number }}

      - name: Copy Anypoint Exchange documentation
        run: |
          cp -Rfpv README.md exchange-docs/home.md
          cp -Rfpv docs/*.* exchange-docs/docs/*.* 

      - id: configuration-tests
        name: Get configuration file for test cases
        uses: jpontdia/devops-pipelines/packages/configuration-file@main
        with:
          configuration-access-token: $configuration_access_token
          yaml-path: ".test-properties"
          prefix: ""
          suffix: ""
      
      - name: Compile code
        # I am using an environment variable just for testing dinamic content execution
        run: $MavenCompile

      - name: Run test cases and package
        run: |
          ## Get the git commit hash 
          commitHash=$(git rev-parse --short "$GITHUB_SHA")

          echo "Test properties: ${{ steps.configuration-tests.outputs.configuration-data }}"
          mvn package -DskipTests ${{ steps.configuration-tests.outputs.configuration-data }}

      - name: Deploy to anypoint exchange
        if: ${{ false }}    
        run: |
          ## Deploy to anypoint exchange
          mvn deploy -DskipTests 

      - name: Publish - MUnit Application Coverage Report
        if: ${{ false }}
        uses: actions/upload-artifact@master
        with:
          name: munit-application-coverage-report
          path: target/site/munit/coverage/*
      
      - name: Publish - MUnit Report
        if: ${{ false }}    
        uses: actions/upload-artifact@master
        with:
          name: munit-test-report
          path: target/surefire-reports/*

      - name: Publish - JAR 
        uses: actions/upload-artifact@master
        with:
          name: jar
          path: target/*.jar

      - name: Publish - POM 
        uses: actions/upload-artifact@master
        with:
          name: pom
          path: pom.xml
















  deploy-dev:
    name: Development
    needs: [build]
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: 'https://dev.myapp.com'
    steps:
      - name: Get JAR file
        uses: actions/download-artifact@v2
        with:
          name: jar

      - name: Get POM file
        uses: actions/download-artifact@v2
        with:
          name: pom

      - name: Get secrets
        uses: jpontdia/devops-pipelines/packages/get-secrets@main
        with:
          keyvault-key: jpworks-keyvault
          azure-credentials: ${{ secrets.azure-credentials }}

      - id: install-anypoint-cli
        name: Install Mulesoft Anypoint CLI
        uses: jpontdia/devops-pipelines/packages/install-anypoint-cli@main

      - id: configuration-cloudhub
        name: Get the configuration for cloud deployment
        uses: jpontdia/devops-pipelines/packages/configuration-file@main
        with:
          configuration-access-token: $configuration_access_token
          yaml-path: ".cloudhub"
          prefix: ""
          suffix: "-dev"

      - id: configuration-service
        name: Get the configuration for the service
        uses: jpontdia/devops-pipelines/packages/configuration-file@main
        with:
          configuration-access-token: $configuration_access_token
          yaml-path: ".properties"
          prefix: ""
          suffix: "-dev"
  
      - id: configuration-deployment-name
        name: Get the configuration for the service
        uses: jpontdia/devops-pipelines/packages/configuration-file@main
        with:
          configuration-access-token: $configuration_access_token
          yaml-path: ".deployment-name"
          prefix: ""
          suffix: "-dev"

      - id: service-info
        name: Get the pom service information
        uses: jpontdia/devops-pipelines/packages/service-info@main

      - id: deployment-development
        name: Deploy the service to dev environment
        uses: jpontdia/devops-pipelines/packages/deployment-cloudhub@main
        with:
          deployment-name: "${{ steps.configuration-deployment-name.outputs.configuration-data }}"
          connectedapp-clientid: "$cicd_connectedapp_clientid"
          connectedapp-secret: "$cicd_connectedapp_secret" 
          configuration-cloud: "${{ steps.configuration-cloudhub.outputs.configuration-data }}"
          configuration-service: "${{ steps.configuration-service.outputs.configuration-data }}"