##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: deployment
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  release:
    if: github.actor == 'jpontdia' || github.actor == 'GitHubActions'
    name: deployment
    runs-on: ubuntu-latest
    steps:

      - name: Get the release metadata
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}      
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Get the release metadata "
          echo "***********************************************"
          echo "Values from github context: "
          echo "  Issue number: ${{ github.event.issue.number}}"
          echo "  Title: ${{ github.event.issue.title}}"
          echo '  Labels: ${{ toJson(github.event.issue.labels) }}'
          echo "  Repository: ${{ github.repository }}"
          echo " "
          line=$(echo "${{ github.event.issue.title}}")
          action="$(cut -d' ' -f1 <<<$line)"
          deployment_environment="$(cut -d' ' -f2 <<< $line)"
          service="$(cut -d' ' -f3 <<< $line)"
          version="$(cut -d' ' -f4 <<< $line)"
          echo "Values from issue title:"
          echo "  Action: $action"
          echo "  Environment: $deployment_environment"
          echo "  Service: $service"
          echo "  Version: $version"
          echo "deployment_environment=$deployment_environment" >> $GITHUB_ENV
          echo "deployment_version=$version" >> $GITHUB_ENV
          echo "deployment_service=$service" >> $GITHUB_ENV

      - name: Get the source code
        uses: actions/checkout@v4
        with:
          ref: '${{env.deployment_version}}'

      - name: Debug - Review the source code
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Debug - Review the source code "
          echo "***********************************************"
          echo " "
          cat pom.xml

      - name: Get global configuration for the pipeline
        uses: jpontdia/common-devops/packages/configuration-service@main
        with:
          keyvault-key: ${{ inputs.keyvault-key }}
          azure-credentials: ${{ inputs.azure-credentials }}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          configurations-repository: ${{ env.CONFIGURATIONS_REPOSITORY }}
          environment: ${{ env.deployment_environment }}

      - id: verify-deployment
        name: Deployment dev - Verify if asset has the configuration
        shell: bash
        run: |
          echo " "
          echo "*****************************************************"
          echo "Verify deployment to ${{ env.deployment_environment }} "
          echo "*****************************************************"
          echo " "      
          echo "dev cloudhub: ${{ env.configuration_cloudhub }}"
          if [ "${{ env.configuration_cloudhub }}" != "" ] ; then
            echo "deployment=true" >> $GITHUB_OUTPUT
            echo "The service has the configuration to deploy in ${{ env.deployment_environment }} environment"
          else
            echo "deployment=false" >> $GITHUB_OUTPUT
            echo "The mulesoft asset doesn't have any deployment configuration"
          fi
                    
      - name: Get jar file
        uses: dsaltares/fetch-gh-release-asset@master
        if: steps.verify-deployment.outputs.deployment == 'true'
        with:
          repo: '${{ github.repository }}'
          version: 'tags/${{ env.deployment_version }}'
          regex: true
          file: "${{ env.deployment_service }}-.*\\.jar"
          token: ${{ secrets.GITHUB_TOKEN }}