##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: Debug
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Debug "
          echo "***********************************************"
          echo " "