##########################################################################
# CICD Pipeline
##########################################################################

# Configuration for this template:
# 1.- Replace the predefined repository jpontdia/common-devops with your own.
# 2.- Update the global environment variables for the script 

name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  GITHUB_ORGANIZATION: jpontdia
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  release:
    name: Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}      
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Debug "
          echo "***********************************************"
          echo " "
          echo "issue.number: ${{ github.event.issue.number}}"
          echo " "
          echo "Title: ${{ github.event.issue.title}}"
          echo " "
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"
          echo " "
          echo " "
          echo " "
          echo " "
          echo "$GITHUB_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"